name: Build and Deploy

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust the Node.js version as needed

      - name: Install Dependencies
        run: npm install  # Or use yarn if you prefer

      - name: Build Project
        run: npm run build  # Or the command to build your project

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Hosting Service
        # Add your deployment steps here, such as deploying to GitHub Pages, Netlify, Vercel, etc.
